// GENERATED by build.js from lib modules + src/bookmarklet.bootstrap.js -- DO NOT EDIT.
// Regenerate: node build.js
(function () {
'use strict';
// ---- lib/normalize.js ----
// Pure text helpers shared by the scorer and the pack schema. No DOM, no deps.

// Deliberately small. Form-field words like "name", "id", "value" are meaningful
// signal here, so they are NOT stopwords.
const STOPWORDS = new Set([
  'the', 'a', 'an', 'your', 'you', 'please', 'enter', 'this',
  'and', 'or', 'of', 'to', 'in', 'for', 'is', 'are', 'if',
  'optional', 'required',
]);

const COMBINING_MARKS = /[̀-ͯ]/g;
const NON_ALNUM = /[^a-z0-9 ]+/g;

function normalizeText(s) {
  return String(s == null ? '' : s)
    .toLowerCase()
    .normalize('NFKD')
    .replace(COMBINING_MARKS, '')
    .replace(/[_\-]+/g, ' ')
    .replace(NON_ALNUM, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function tokenize(s) {
  const n = normalizeText(s);
  if (!n) return [];
  return n.split(' ').filter((t) => t && !STOPWORDS.has(t));
}

function tokenSet(...parts) {
  const set = new Set();
  for (const p of parts) {
    for (const t of tokenize(p)) set.add(t);
  }
  return set;
}

function overlapCount(aSet, bSet) {
  let n = 0;
  for (const t of aSet) if (bSet.has(t)) n++;
  return n;
}
// ---- lib/policy.js ----
// Whether a PACK field may be proposed (before any page match / confidence).
//
// `sensitive:true` does NOT make a field non-proposable. Agent A uses it for
// ordinary contact details (email, phone). It only means "individual
// confirmation is always required" -- which this extension enforces for every
// field regardless.
//
// Legal attestations, e-signatures, government IDs, payment/banking, medical and
// demographic/EEO fields are handled by the backend OMITTING them from the pack
// plus the page-field classifier (lib/classify.js). This module never sees them.
//
// Rules:
//   - status === "needs_input"            -> never proposable
//   - answer_kind === "declared_answer"   -> proposable ONLY when
//        source === "user_supplied" AND status === "sourced"
//   - answer_kind === "narrative"         -> proposable ONLY when the pack is
//        reviewed (still requires individual acceptance)
//   - standard fields                     -> proposable when
//        source in {profile, user_supplied}
//   - a non-empty value is required (enforced upstream in normalizeField)

const PROFILE_SOURCES = new Set(['profile', 'user_supplied']);

/**
 * @param {{source?:string, answerKind?:string, status?:string,
 *          sensitive?:boolean, reviewed?:boolean}} field
 * @returns {{proposable:boolean, reason:string}}
 */
function decideProposable(field) {
  const no = (reason) => ({ proposable: false, reason });
  const yes = (reason) => ({ proposable: true, reason });

  const source = String(field.source || '').toLowerCase();
  const kind = String(field.answerKind || 'standard').toLowerCase();
  const status = String(field.status || '').toLowerCase();
  const reviewed = field.reviewed === true;

  if (status === 'needs_input') return no('needs_input');

  if (kind === 'declared_answer') {
    if (source !== 'user_supplied') return no('declared_not_user_supplied');
    if (status !== 'sourced') return no('declared_not_sourced');
    return yes('declared_ok');
  }

  if (kind === 'narrative') {
    return reviewed ? yes('narrative_reviewed_pack') : no('narrative_unreviewed_pack');
  }

  // standard
  return PROFILE_SOURCES.has(source) ? yes('standard_sourced') : no('standard_unsourced');
}
// ---- lib/packschema.js ----
// Pack-payload validation: schema-version gate, envelope shape, per-field
// normalization + hardening. Used by lib/adapter.js (service worker) and by the
// bookmarklet fallback (which parses pasted JSON).
//
// Agent A's contract is final:
//   - schema_version is the integer 1
//   - pack_id / tracked_application_id are positive integers
//   - reviewed is the fail-closed authoritative reviewed state
//   - fields is an array; each field object has exactly:
//       key, label, value, type, autocomplete, source, answer_kind,
//       status, provenance, sensitive
//   - field types include "textarea"


const SUPPORTED_SCHEMA_VERSION = 1;

class ContractError extends Error {
  constructor(detail) {
    super(detail || 'contract_mismatch');
    this.name = 'ContractError';
  }
}

const FIELD_TYPES = new Set([
  'text', 'email', 'tel', 'url', 'number', 'date', 'textarea', 'select',
]);
const MAX_VALUE_LEN = 20000;
const FORBIDDEN_KEYS = new Set(['__proto__', 'constructor', 'prototype']);

function safePlainCopy(obj) {
  const out = {};
  for (const k of Object.keys(obj)) {
    if (FORBIDDEN_KEYS.has(k)) continue;
    out[k] = obj[k];
  }
  return out;
}

function hardenValue(raw) {
  if (typeof raw === 'number' && Number.isFinite(raw)) raw = String(raw);
  if (typeof raw !== 'string') return null;
  // drop C0/C1 control chars, keeping only TAB (\x09) and LF (\x0a)
  let v = raw.replace(/[\x00-\x08\x0b-\x1f\x7f]/g, '');
  if (v.length > MAX_VALUE_LEN) v = v.slice(0, MAX_VALUE_LEN);
  return v;
}

/**
 * Normalize one raw pack-field entry. Returns null if unusable (caller counts
 * these as "omitted"). `packReviewed` is the authoritative reviewed state and
 * gates narrative fields.
 */
function normalizeField(entry, packReviewed) {
  if (!entry || typeof entry !== 'object' || Array.isArray(entry)) return null;
  const e = safePlainCopy(entry);

  const label = typeof e.label === 'string' ? e.label.trim() : '';
  const type = typeof e.type === 'string' ? e.type.trim().toLowerCase() : '';
  const value = hardenValue(e.value);

  if (!label || !FIELD_TYPES.has(type) || value == null || value.trim() === '') {
    return null;
  }

  const key = typeof e.key === 'string' && e.key.trim() ? e.key.trim() : null;
  const autocompleteHint =
    typeof e.autocomplete === 'string' && e.autocomplete.trim()
      ? e.autocomplete.trim().toLowerCase()
      : null;
  const source = typeof e.source === 'string' ? e.source.trim().toLowerCase() : '';
  const answerKind =
    typeof e.answer_kind === 'string' ? e.answer_kind.trim().toLowerCase() : 'standard';
  const status = typeof e.status === 'string' ? e.status.trim().toLowerCase() : '';
  const provenance = typeof e.provenance === 'string' ? e.provenance.trim() : '';
  const sensitive = e.sensitive === true;

  const decision = decideProposable({
    source,
    answerKind,
    status,
    sensitive,
    reviewed: packReviewed === true,
  });

  return {
    key,
    label,
    value,
    type,
    autocompleteHint,
    source,
    answerKind,
    status,
    provenance,
    sensitive,
    proposable: decision.proposable,
    policyReason: decision.reason,
  };
}

/**
 * Validate + normalize an /autofill payload (or the bookmarklet's pasted JSON).
 * Throws ContractError on envelope-level drift. An explicit empty `fields: []` is
 * valid; a missing or non-array `fields` is drift.
 *
 * @returns {{schemaVersion:number, reviewed:boolean, fields:object[],
 *            omittedCount:number}}
 */
function normalizeAutofill(raw) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    throw new ContractError('autofill payload is not an object');
  }
  if (raw.schema_version !== SUPPORTED_SCHEMA_VERSION) {
    throw new ContractError('unsupported or missing schema_version');
  }
  if (!('fields' in raw) || !Array.isArray(raw.fields)) {
    throw new ContractError('fields is missing or not an array');
  }

  const reviewed = raw.reviewed === true; // fail closed
  const fields = [];
  let omittedCount = 0;
  for (const entry of raw.fields) {
    const nf = normalizeField(entry, reviewed);
    if (nf) fields.push(nf);
    else omittedCount += 1;
  }

  return { schemaVersion: raw.schema_version, reviewed, fields, omittedCount };
}

/**
 * Tighten proposability once the FINAL reviewed state is known (pack meta AND
 * autofill payload must agree; disagreement -> unreviewed). Narrative fields
 * flip to non-proposable if the final state is unreviewed. Monotonic: never
 * loosens a decision.
 */
function applyReviewedGate(fields, finalReviewed) {
  if (finalReviewed === true) return fields;
  return fields.map((f) =>
    f.answerKind === 'narrative' && f.proposable
      ? { ...f, proposable: false, policyReason: 'narrative_unreviewed_pack' }
      : f,
  );
}
// ---- lib/scoring.js ----
// Match pack fields to page fields. Deterministic and order-independent.
//
// A proposal is only "proposable" (Accept enabled) when ALL hold:
//   - pack field is policy-proposable (lib/policy)
//   - page field type is compatible
//   - there is a MEANINGFUL token/autocomplete match (score alone never qualifies)
//   - confidence >= MIN_CONFIDENCE
//   - not ambiguous (no close runner-up, no other pack field claiming the same
//     page field as its top match)
// Otherwise it is preview-only or omitted.


const PREVIEW_FLOOR = 0.45; // below this: omit entirely
const MIN_CONFIDENCE = 0.62; // below this (but >= floor): preview-only
const AMBIGUITY_DELTA = 0.12; // top two within this: ambiguous

// pack type -> acceptable page field types
const TYPE_COMPAT = {
  text: new Set(['text', 'search']),
  email: new Set(['email', 'text']),
  tel: new Set(['tel', 'text']),
  url: new Set(['url', 'text']),
  number: new Set(['number', 'text']),
  date: new Set(['date', 'text']),
  textarea: new Set(['textarea']),
  select: new Set(['select']),
};

const AUTOCOMPLETE_HINTS = {
  name: ['name', 'fullname', 'full_name'],
  'given-name': ['first', 'firstname', 'first_name', 'given'],
  'family-name': ['last', 'lastname', 'last_name', 'surname', 'family'],
  email: ['email'],
  tel: ['phone', 'telephone', 'mobile', 'tel'],
  'tel-national': ['phone', 'telephone', 'tel'],
  url: ['website', 'portfolio', 'url', 'site'],
  'street-address': ['address', 'street'],
  'address-line1': ['address', 'street'],
  'postal-code': ['postcode', 'zip', 'postal'],
  'address-level2': ['city', 'town'],
  country: ['country'],
  organization: ['company', 'employer', 'organization'],
  'organization-title': ['title', 'role', 'position'],
};

function norm(s) {
  return String(s == null ? '' : s).toLowerCase().replace(/\s+/g, ' ').trim();
}

function typeCompatible(packType, pageInputType) {
  const allowed = TYPE_COMPAT[packType];
  return !!allowed && allowed.has(pageInputType);
}

/**
 * Score a single (packField, pageDescriptor) pair.
 * @returns {{score:number, meaningful:boolean, reasons:string[]}}
 */
function scorePair(packField, d) {
  if (!typeCompatible(packField.type, d.inputType)) {
    return { score: 0, meaningful: false, reasons: ['type_incompatible'] };
  }

  const reasons = [];
  let score = 0;
  let meaningful = false;

  const packTokens = tokenSet(packField.key || '', packField.label || '');
  const labelTokens = tokenSet(d.label);
  const nameIdTokens = tokenSet(d.name, d.id);
  const softTokens = tokenSet(d.placeholder, d.ariaLabel);

  const ac = d.autocomplete;
  if (ac && packField.autocompleteHint && ac === packField.autocompleteHint) {
    score += 0.7;
    meaningful = true;
    reasons.push('autocomplete_exact');
  } else if (ac && AUTOCOMPLETE_HINTS[ac]) {
    const hints = AUTOCOMPLETE_HINTS[ac];
    const key = norm(packField.key).replace(/[\s_-]+/g, '');
    // Require the pack key to *equal* a hint token (modulo separators), not merely
    // contain it -- autocomplete="name" must not hint-match key "first_name".
    if (key && hints.some((h) => key === h.replace(/[\s_-]+/g, ''))) {
      score += 0.55;
      meaningful = true;
      reasons.push('autocomplete_hint');
    }
  }

  const labelOverlap = overlapCount(packTokens, labelTokens);
  if (labelOverlap > 0) {
    score += Math.min(0.6, 0.3 * labelOverlap);
    meaningful = true;
    reasons.push('label_overlap:' + labelOverlap);
  }

  const nameOverlap = overlapCount(packTokens, nameIdTokens);
  if (nameOverlap > 0) {
    score += Math.min(0.5, 0.28 * nameOverlap);
    meaningful = true;
    reasons.push('name_overlap:' + nameOverlap);
  }

  const softOverlap = overlapCount(packTokens, softTokens);
  if (softOverlap > 0) {
    score += Math.min(0.3, 0.15 * softOverlap);
    reasons.push('soft_overlap:' + softOverlap); // soft-only match is NOT meaningful
  }

  return { score: Math.min(1, score), meaningful, reasons };
}

/**
 * For a native <select>, decide which option (if any) a pack value maps to.
 * Compares options ONLY against the pack field's proposed `value` -- never
 * against the field label (a label like "Work authorisation" is not an option
 * like "Yes"). Never returns a disabled option; never invents one; never
 * defaults to the first option.
 * @returns {{status:'ok', option:object} | {status:'ambiguous', options:object[]}
 *   | {status:'no_option'} | {status:'disabled_only'} | {status:'not_select'}}
 */
function resolveSelectOption(packField, d) {
  if (d.inputType !== 'select' || !Array.isArray(d.options)) return { status: 'not_select' };

  const want = norm(packField.value);
  if (!want) return { status: 'no_option' };

  const matches = d.options.filter(
    (o) => !o.disabled && (norm(o.value) === want || norm(o.text) === want),
  );

  const chosen = dedupe(matches);
  if (chosen.length === 1) return { status: 'ok', option: chosen[0] };
  if (chosen.length > 1) return { status: 'ambiguous', options: chosen };

  const disabledMatch = d.options.some(
    (o) => o.disabled && (norm(o.value) === want || norm(o.text) === want),
  );
  return { status: disabledMatch ? 'disabled_only' : 'no_option' };
}

function dedupe(opts) {
  const seen = new Set();
  const out = [];
  for (const o of opts) {
    const k = o.value + ' ' + o.text;
    if (!seen.has(k)) {
      seen.add(k);
      out.push(o);
    }
  }
  return out;
}

function round2(n) {
  return Math.round(n * 100) / 100;
}

/**
 * Build the proposal list.
 * @param {object[]} packFields  NormalizedField[]
 * @param {object[]} pageFields  fillable descriptors from classify.scanFields
 * @returns {object[]} proposals
 */
function buildProposals(packFields, pageFields) {
  const perPack = new Map(); // pi -> candidate[] sorted desc

  packFields.forEach((pf, pi) => {
    const candidates = [];
    pageFields.forEach((d, gi) => {
      const r = scorePair(pf, d);
      if (r.score > 0 && r.meaningful) {
        candidates.push({ gi, score: r.score, reasons: r.reasons });
      }
    });
    candidates.sort((a, b) => b.score - a.score || a.gi - b.gi);
    if (candidates.length) perPack.set(pi, candidates);
  });

  // page fields that are the #1 pick of more than one *proposable* pack field.
  // A preview-only / non-proposable pack field can never be written, so it does
  // not contend for a target and must not push a fillable field into ambiguity.
  const topClaims = new Map(); // gi -> count
  for (const [pi, list] of perPack) {
    if (!packFields[pi].proposable) continue;
    const gi = list[0].gi;
    topClaims.set(gi, (topClaims.get(gi) || 0) + 1);
  }

  const proposals = [];
  for (const [pi, list] of perPack) {
    const pf = packFields[pi];
    const best = list[0];
    const second = list[1];

    if (best.score < PREVIEW_FLOOR) continue; // omit

    const contested = (topClaims.get(best.gi) || 0) > 1;
    const closePair = !!second && best.score - second.score < AMBIGUITY_DELTA;
    const acceptableIfPicked = pf.proposable && best.score >= MIN_CONFIDENCE;

    let state;
    if (!pf.proposable) state = 'preview';
    else if (contested || closePair) state = 'ambiguous'; // user must pick a target
    else if (best.score < MIN_CONFIDENCE) state = 'preview';
    else state = 'proposable';

    let selectResolution = null;
    if (pf.type === 'select') {
      selectResolution = resolveSelectOption(pf, pageFields[best.gi]);
      if (selectResolution.status === 'no_option' || selectResolution.status === 'disabled_only') {
        continue; // never propose a value with no real enabled option
      }
      if (selectResolution.status === 'ambiguous' && state === 'proposable') {
        state = 'ambiguous';
      }
    }

    proposals.push({
      packIndex: pi,
      packKey: pf.key,
      packLabel: pf.label,
      value: pf.value,
      type: pf.type,
      source: pf.source,
      answerKind: pf.answerKind,
      status: pf.status,
      provenance: pf.provenance,
      sensitive: pf.sensitive,
      policyReason: pf.policyReason,
      proposablePolicy: pf.proposable,
      state,
      acceptableIfPicked,
      confidence: round2(best.score),
      targetPageIndex: state === 'ambiguous' ? null : best.gi,
      selectResolution,
      candidates: list.slice(0, 4).map((c) => ({
        pageIndex: c.gi,
        score: round2(c.score),
        label:
          pageFields[c.gi].label ||
          pageFields[c.gi].name ||
          pageFields[c.gi].id ||
          `field #${c.gi + 1}`,
      })),
    });
  }

  proposals.sort((a, b) => {
    const ai = a.targetPageIndex == null ? Number.MAX_SAFE_INTEGER : a.targetPageIndex;
    const bi = b.targetPageIndex == null ? Number.MAX_SAFE_INTEGER : b.targetPageIndex;
    return ai - bi || a.packIndex - b.packIndex;
  });

  return proposals;
}
// ---- lib/classify.js ----
// Page-field scanning + exclusion taxonomy.
//
// The security-critical part -- deciding whether a field is off-limits -- is the
// pure function classifyDescriptor(descriptor). scanFields(root) is a thin DOM
// walk that builds descriptors and calls it.

// input types we will ever write a value into
const FILLABLE_INPUT_TYPES = new Set([
  'text', 'email', 'tel', 'url', 'number', 'search', 'date', '',
]);

// input types we hard-exclude by type alone
const EXCLUDED_INPUT_TYPES = new Set([
  'password', 'hidden', 'file', 'submit', 'reset', 'button', 'image',
  'checkbox', 'radio',
]);

// label/name/id/placeholder/aria text patterns that make a field off-limits
// regardless of the pack. Categories mirror lib/policy.HARD_EXCLUDED_CATEGORIES.
const SENSITIVE_PATTERNS = [
  {
    cat: 'payment',
    re: /\b(card\s*number|cardnumber|cc[-\s]?num(ber)?|cvv|cvc2?|security\s*code|iban|sort[-\s]?code|routing\s*(number|no)|account\s*(number|no)|bank\s*account|billing\s*address)\b/i,
  },
  {
    cat: 'gov_id',
    re: /\b(national\s*insurance|ni\s*number|social\s*security|ssn|passport\s*(no|number)|driver'?s?\s*licen[cs]e|tax\s*(id|identification|file\s*number)|itin|\bein\b)\b/i,
  },
  {
    cat: 'medical',
    re: /\b(disab(led|ility)|medical\s*(condition|history|information)|health\s*condition|impairment|chronic\s*illness|accommodation\s*request|mental\s*health)\b/i,
  },
  {
    cat: 'eeo',
    re: /(\brace\b|ethnic(ity)?|gender\s*identity|\bsex\b|sexual\s*orientation|\bveteran\b|disability\s*status|protected\s*(class|group|veteran)|equal\s*(employment\s*)?opportunity|\beeo\b|self[-\s]?identif|hispanic\s*or\s*latino)/i,
  },
  {
    cat: 'signature',
    re: /\b(e[-\s]?signature|electronic\s*signature|digital\s*signature|sign\s*here|type\s*your\s*(full\s*)?name\s*to\s*sign|^signature$)\b/i,
  },
  {
    cat: 'legal',
    re: /(i\s*(certify|attest|declare|acknowledge|consent|agree)\b|terms\s*(and|&)\s*conditions|privacy\s*policy|legal\s*(declaration|attestation)|penalty\s*of\s*perjury|under\s*penalty|authoriz(e|ation)\s*to\s*(check|verify|contact)|background\s*check\s*consent)/i,
  },
];

const CAPTCHA_SELECTORS = [
  '.g-recaptcha',
  'iframe[src*="recaptcha"]',
  'iframe[src*="google.com/recaptcha"]',
  '.h-captcha',
  'iframe[src*="hcaptcha"]',
  '.cf-turnstile',
  '#px-captcha',
  '[data-sitekey]',
];

/**
 * Pure classification.
 * @param {object} d descriptor: { tag, inputType, label, name, id, placeholder,
 *   ariaLabel, autocomplete, disabled, readOnly, insideCaptcha }
 * @returns {{fillable:boolean, excludedReason:(string|null)}}
 */
function classifyDescriptor(d) {
  const tag = String(d.tag || '').toLowerCase();
  const inputType = String(d.inputType || '').toLowerCase();

  if (tag === 'input' && EXCLUDED_INPUT_TYPES.has(inputType)) {
    return excl('field_type:' + inputType);
  }
  if (tag === 'input' && !FILLABLE_INPUT_TYPES.has(inputType)) {
    return excl('unsupported_type:' + (inputType || 'unknown'));
  }
  if (tag !== 'input' && tag !== 'textarea' && tag !== 'select') {
    return excl('not_fillable_tag:' + tag);
  }
  if (d.disabled) return excl('disabled');
  if (d.readOnly) return excl('readonly');
  if (d.insideCaptcha) return excl('captcha');

  const hay = [d.label, d.name, d.id, d.placeholder, d.ariaLabel]
    .map((x) => String(x || ''))
    .join('  ');
  for (const p of SENSITIVE_PATTERNS) {
    if (p.re.test(hay)) return excl('sensitive:' + p.cat);
  }

  return { fillable: true, excludedReason: null };

  function excl(reason) {
    return { fillable: false, excludedReason: reason };
  }
}

function cssEscapeAttr(s) {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') return CSS.escape(s);
  return String(s).replace(/["\\\]]/g, '\\$&');
}

function labelTextFor(el, root) {
  const bits = [];
  const id = el.getAttribute && el.getAttribute('id');
  if (id) {
    try {
      const labels = root.querySelectorAll(`label[for="${cssEscapeAttr(id)}"]`);
      labels.forEach((l) => bits.push(l.textContent || ''));
    } catch {
      /* bad id -> skip */
    }
  }
  const wrap = el.closest ? el.closest('label') : null;
  if (wrap) bits.push(wrap.textContent || '');

  const lb = el.getAttribute && el.getAttribute('aria-labelledby');
  if (lb && root.getElementById) {
    lb.split(/\s+/).forEach((rid) => {
      const n = root.getElementById(rid);
      if (n) bits.push(n.textContent || '');
    });
  }
  return bits.join(' ').replace(/\s+/g, ' ').trim();
}

function insideCaptcha(el) {
  if (!el.closest) return false;
  return CAPTCHA_SELECTORS.some((s) => {
    try {
      return !!el.closest(s);
    } catch {
      return false;
    }
  });
}

/**
 * Walk a document/root and return { fillable: descriptor[], excluded: descriptor[] }.
 * Descriptors keep a live `el` reference for later writing.
 */
function scanFields(root) {
  const doc = root || (typeof document !== 'undefined' ? document : null);
  if (!doc) return { fillable: [], excluded: [] };

  const fillable = [];
  const excluded = [];
  const nodes = doc.querySelectorAll('input, textarea, select');

  nodes.forEach((el, index) => {
    const tag = el.tagName.toLowerCase();
    let inputType = (el.getAttribute('type') || '').toLowerCase();
    if (tag === 'input' && inputType === '') inputType = 'text';

    const descriptor = {
      el,
      index,
      tag,
      inputType: tag === 'input' ? inputType : tag,
      label: labelTextFor(el, doc),
      name: el.getAttribute('name') || '',
      id: el.getAttribute('id') || '',
      placeholder: el.getAttribute('placeholder') || '',
      ariaLabel: el.getAttribute('aria-label') || '',
      autocomplete: (el.getAttribute('autocomplete') || '').toLowerCase(),
      disabled: !!el.disabled,
      readOnly: !!el.readOnly,
      insideCaptcha: insideCaptcha(el),
      options:
        tag === 'select'
          ? Array.from(el.options || []).map((o) => ({
              value: o.value,
              text: (o.textContent || '').trim(),
              disabled: !!o.disabled,
            }))
          : null,
    };

    const verdict = classifyDescriptor(descriptor);
    if (verdict.fillable) {
      fillable.push(descriptor);
    } else {
      descriptor.excludedReason = verdict.excludedReason;
      excluded.push(descriptor);
    }
  });

  return { fillable, excluded };
}

function hasCaptcha(root) {
  const doc = root || (typeof document !== 'undefined' ? document : null);
  if (!doc) return false;
  return CAPTCHA_SELECTORS.some((s) => {
    try {
      return !!doc.querySelector(s);
    } catch {
      return false;
    }
  });
}
// ---- lib/overlay.js ----
// In-page review overlay. Shadow-DOM isolated, idempotent, text-only rendering.
//
// This module NEVER submits, never calls requestSubmit, never clicks a button,
// never focuses/blurs, never navigates, never touches file or CAPTCHA controls.
// On Accept it dispatches exactly one 'input' and one 'change' event.

const HOST_ID = '__jobradar_autofill_overlay_host__';

const SAFE_TAGS = new Set(['INPUT', 'TEXTAREA', 'SELECT']);
const SAFE_INPUT_TYPES = new Set(['text', 'email', 'tel', 'url', 'number', 'search', 'date', '']);

class RefusedWrite extends Error {
  constructor(msg) {
    super(msg || 'refused');
    this.name = 'RefusedWrite';
  }
}

/**
 * Hard runtime guard. Refuses anything that is not a plain fillable control,
 * even if upstream classification failed. Dispatches only input + change.
 */
function writeValue(el, value) {
  if (!el || !SAFE_TAGS.has(el.tagName)) throw new RefusedWrite('not a fillable element');
  if (typeof el.closest === 'function' && el.closest('button')) {
    throw new RefusedWrite('inside a <button>');
  }
  if (el.disabled || el.readOnly) throw new RefusedWrite('disabled or readonly');

  if (el.tagName === 'INPUT') {
    const t = String(el.getAttribute && el.getAttribute('type') || '').toLowerCase();
    if (!SAFE_INPUT_TYPES.has(t)) throw new RefusedWrite('input type: ' + (t || 'unknown'));
  }

  if (el.tagName === 'SELECT') {
    const opts = Array.from(el.options || []);
    const match = opts.find((o) => !o.disabled && o.value === value);
    if (!match) throw new RefusedWrite('no matching enabled <option>');
    el.value = value;
  } else {
    el.value = value;
  }

  el.dispatchEvent(new Event('input', { bubbles: true }));
  el.dispatchEvent(new Event('change', { bubbles: true }));
  return true;
}

function removeOverlay(doc) {
  const d = doc || (typeof document !== 'undefined' ? document : null);
  if (!d) return;
  const prev = d.getElementById(HOST_ID);
  if (prev && prev.parentNode) prev.parentNode.removeChild(prev);
}

function mk(doc, tag, className, text) {
  const n = doc.createElement(tag);
  if (className) n.className = className;
  if (text != null) n.textContent = String(text);
  return n;
}

const OVERLAY_CSS = `
:host { all: initial; }
.wrap {
  position: fixed; top: 12px; right: 12px; width: 340px; max-height: 82vh;
  overflow: auto; z-index: 2147483647;
  font: 13px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  color: #1a1a1a; background: #fff; border: 1px solid #c9c9c9; border-radius: 10px;
  box-shadow: 0 8px 30px rgba(0,0,0,.22); padding: 12px;
}
.warn { background: #fff4e5; border: 1px solid #f0c27b; border-radius: 6px;
  padding: 8px; margin-bottom: 10px; font-weight: 600; }
.head { font-size: 14px; margin-bottom: 8px; }
.role { color: #555; font-weight: 400; }
.badge { border-radius: 6px; padding: 6px 8px; margin-bottom: 8px; font-weight: 600; }
.badge.preview { background: #eef2ff; border: 1px solid #c7d2fe; }
.note { color: #555; margin-bottom: 8px; }
.row { border: 1px solid #e3e3e3; border-radius: 8px; padding: 8px; margin-bottom: 8px; }
.row .k { font-weight: 600; }
.row .v { color: #333; word-break: break-word; margin: 3px 0; }
.row .meta { color: #666; font-size: 12px; }
.row.filled { background: #ecfdf3; border-color: #a6e9c5; }
.row.skipped { opacity: .55; }
.row.previewonly { background: #f7f7f8; }
.row .err { color: #b42318; font-size: 12px; margin-top: 4px; }
.btns { margin-top: 6px; display: flex; gap: 6px; flex-wrap: wrap; }
button { font: inherit; padding: 4px 10px; border-radius: 6px; border: 1px solid #b9b9b9;
  background: #f6f6f6; cursor: pointer; }
button.accept { background: #1f6feb; border-color: #1f6feb; color: #fff; }
button.accept[disabled] { background: #c7c7c7; border-color: #c7c7c7; cursor: not-allowed; }
button.pick { background: #eef2ff; }
.excluded { margin-top: 6px; }
.exrow { color: #666; font-size: 12px; padding: 2px 0; }
.foot { margin-top: 10px; text-align: right; }
`;

/**
 * @param {object} args
 * @param {Document} [args.doc]
 * @param {object} args.pack  NormalizedPack (metadata only used here)
 * @param {object[]} args.proposals
 * @param {object[]} args.pageFields  fillable descriptors (for candidate labels)
 * @param {object[]} args.excluded  excluded descriptors
 * @param {boolean} args.previewOnly  pack unreviewed -> nothing fillable
 * @param {number} args.omittedCount
 * @param {object} args.controller  { onAccept(proposal, pageIndex)->{ok,error?},
 *   onSkip(proposal), onPickTarget(proposal, pageIndex), onClose() }
 */
function renderOverlay(args) {
  const doc = args.doc || document;
  const {
    pack, proposals, pageFields, excluded, previewOnly, omittedCount, controller,
  } = args;

  removeOverlay(doc); // idempotent: exactly one overlay at a time

  const host = doc.createElement('div');
  host.id = HOST_ID;
  host.setAttribute('data-jobradar', 'autofill-overlay');
  const shadow = typeof host.attachShadow === 'function'
    ? host.attachShadow({ mode: 'open' })
    : host;

  shadow.appendChild(mk(doc, 'style', null, OVERLAY_CSS));

  const wrap = mk(doc, 'div', 'wrap');
  wrap.appendChild(mk(doc, 'div', 'warn',
    'Review every field before you submit. This tool never submits forms, never clicks buttons, and never solves CAPTCHAs.'));

  const heading =
    pack.heading ||
    (pack.applicationId ? 'Tracked application #' + pack.applicationId : 'Autofill pack');
  const head = mk(doc, 'div', 'head');
  head.appendChild(mk(doc, 'strong', null, heading));
  wrap.appendChild(head);

  if (previewOnly) {
    wrap.appendChild(mk(doc, 'div', 'badge preview',
      'This pack is not reviewed yet — preview only. Nothing can be filled.'));
  }
  if (omittedCount > 0) {
    wrap.appendChild(mk(doc, 'div', 'note',
      omittedCount + ' unusable answer' + (omittedCount === 1 ? '' : 's') + ' were omitted.'));
  }

  const filledPageIndexes = new Set();

  if (!proposals.length) {
    wrap.appendChild(mk(doc, 'div', 'note', 'No confident matches on this page.'));
  }
  proposals.forEach((p) => {
    wrap.appendChild(buildRow(doc, p, { pageFields, previewOnly, controller, filledPageIndexes }));
  });

  if (excluded && excluded.length) {
    const det = mk(doc, 'details', 'excluded');
    det.appendChild(mk(doc, 'summary', null,
      excluded.length + ' field(s) left untouched (sensitive, file, CAPTCHA, buttons)'));
    excluded.forEach((x) => {
      det.appendChild(mk(doc, 'div', 'exrow',
        (x.label || x.name || x.id || 'field') + ' — ' + (x.excludedReason || 'excluded')));
    });
    wrap.appendChild(det);
  }

  const foot = mk(doc, 'div', 'foot');
  const closeBtn = mk(doc, 'button', 'close', 'Clear and close');
  closeBtn.addEventListener('click', () => controller.onClose());
  foot.appendChild(closeBtn);
  wrap.appendChild(foot);

  shadow.appendChild(wrap);
  (doc.body || doc.documentElement).appendChild(host);
  return { host, shadow };
}

function buildRow(doc, p, ctx) {
  const { pageFields, previewOnly, controller, filledPageIndexes } = ctx;
  const row = mk(doc, 'div', 'row');
  const previewOnlyRow = previewOnly || p.state === 'preview';
  if (previewOnlyRow) row.classList.add('previewonly');

  row.appendChild(mk(doc, 'div', 'k', p.packLabel));
  row.appendChild(mk(doc, 'div', 'v', p.value));

  const src = p.provenance || sourceLabel(p.source, p.answerKind);
  row.appendChild(mk(doc, 'div', 'meta',
    'Source: ' + src + '  ·  confidence ' + p.confidence
    + (p.sensitive ? '  ·  sensitive — always confirm' : '')
    + (previewOnlyRow ? '  ·  preview only' : '')));

  const errLine = mk(doc, 'div', 'err');
  errLine.hidden = true;
  row.appendChild(errLine);

  const btns = mk(doc, 'div', 'btns');

  if (p.state === 'ambiguous') {
    row.appendChild(mk(doc, 'div', 'meta', 'Ambiguous — choose the field to fill:'));
    p.candidates.forEach((c) => {
      const b = mk(doc, 'button', 'pick', truncate(c.label, 40) + '  (' + c.score + ')');
      b.addEventListener('click', () => {
        p.state = p.acceptableIfPicked ? 'proposable' : 'preview';
        p.targetPageIndex = c.pageIndex;
        controller.onPickTarget(p, c.pageIndex);
        rerenderRow(row, p, ctx);
      });
      btns.appendChild(b);
    });
    row.appendChild(btns);
    return row;
  }

  const acceptBtn = mk(doc, 'button', 'accept', 'Accept');
  const skipBtn = mk(doc, 'button', null, 'Skip');

  const canAccept = !previewOnlyRow && p.state === 'proposable' && p.targetPageIndex != null;
  if (!canAccept) acceptBtn.setAttribute('disabled', 'disabled');

  acceptBtn.addEventListener('click', () => {
    if (acceptBtn.hasAttribute('disabled')) return;
    if (filledPageIndexes.has(p.targetPageIndex)) {
      showErr(errLine, 'That field was already filled by another answer.');
      return;
    }
    const res = controller.onAccept(p, p.targetPageIndex);
    if (res && res.ok) {
      filledPageIndexes.add(p.targetPageIndex);
      row.classList.add('filled');
      acceptBtn.setAttribute('disabled', 'disabled');
      skipBtn.setAttribute('disabled', 'disabled');
      errLine.hidden = true;
    } else {
      showErr(errLine, (res && res.error) || 'Could not fill that field.');
    }
  });

  skipBtn.addEventListener('click', () => {
    row.classList.add('skipped');
    acceptBtn.setAttribute('disabled', 'disabled');
    skipBtn.setAttribute('disabled', 'disabled');
    controller.onSkip(p);
  });

  btns.appendChild(acceptBtn);
  btns.appendChild(skipBtn);
  row.appendChild(btns);
  return row;
}

function rerenderRow(oldRow, p, ctx) {
  const doc = oldRow.ownerDocument || document;
  const fresh = buildRow(doc, p, ctx);
  if (oldRow.parentNode) oldRow.parentNode.replaceChild(fresh, oldRow);
}

function showErr(errLine, text) {
  errLine.textContent = text;
  errLine.hidden = false;
}

function sourceLabel(source, kind) {
  if (source === 'profile') return 'your saved profile';
  if (source === 'user_supplied') return 'an answer you supplied';
  if (source === 'cv') return 'your CV (not user-confirmed)';
  if (source === 'generated' || source === 'derived') return 'assistant-generated draft';
  return source || 'unknown';
}

function truncate(s, n) {
  s = String(s || '');
  return s.length > n ? s.slice(0, n - 1) + '…' : s;
}
// ---- src/bookmarklet.bootstrap.js ----
// Bookmarklet bootstrap (concatenated after lib/* by build.js into bookmarklet.js).
//
// LIMITED FALLBACK -- not the production path. This runs in the page's own
// JavaScript environment and is far less isolated than the extension. Prefer the
// extension whenever it is available.
//
// It contacts no backend. On invocation it opens a small overlay with a textarea;
// the user pastes autofill JSON they exported for this session. The JSON is parsed
// with JSON.parse (never eval) and validated against the same schema_version and
// field contract as the extension. The parsed pack is kept only in this closure,
// the textarea is cleared immediately after a successful parse, and "Clear and
// close" drops every reference. No storage of any kind is used.

(function bookmarklet() {
  var pack = null; // closure-only

  function reset() {
    pack = null;
    removeOverlay(document);
  }

  // Drop the pasted pack if the page navigates/unloads while the overlay is open.
  window.addEventListener('pagehide', reset, { once: true });

  function openPasteUI() {
    removeOverlay(document);
    var host = document.createElement('div');
    host.id = HOST_ID;
    var shadow = host.attachShadow ? host.attachShadow({ mode: 'open' }) : host;

    var style = document.createElement('style');
    style.textContent =
      ':host{all:initial}.b{position:fixed;top:12px;right:12px;width:340px;z-index:2147483647;' +
      'font:13px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:#1a1a1a;' +
      'background:#fff;border:1px solid #c9c9c9;border-radius:10px;box-shadow:0 8px 30px rgba(0,0,0,.22);padding:12px}' +
      '.w{background:#fff4e5;border:1px solid #f0c27b;border-radius:6px;padding:8px;margin-bottom:8px;font-weight:600}' +
      'textarea{width:100%;height:120px;font:12px monospace;box-sizing:border-box}' +
      '.e{color:#b42318;margin-top:6px}button{font:inherit;padding:4px 10px;margin-top:8px;margin-right:6px;' +
      'border-radius:6px;border:1px solid #b9b9b9;background:#f6f6f6;cursor:pointer}';
    shadow.appendChild(style);

    var box = document.createElement('div');
    box.className = 'b';

    var warn = document.createElement('div');
    warn.className = 'w';
    warn.textContent =
      'Bookmarklet fallback: runs in this page’s JavaScript context and is less isolated than the extension. It never submits and never contacts a server.';
    box.appendChild(warn);

    var ta = document.createElement('textarea');
    ta.setAttribute('placeholder', 'Paste exported autofill JSON here');
    box.appendChild(ta);

    var err = document.createElement('div');
    err.className = 'e';
    err.hidden = true;
    box.appendChild(err);

    var loadBtn = document.createElement('button');
    loadBtn.textContent = 'Load JSON';
    var closeBtn = document.createElement('button');
    closeBtn.textContent = 'Clear and close';

    loadBtn.addEventListener('click', function () {
      var raw = ta.value;
      var parsed;
      try {
        parsed = JSON.parse(raw);
      } catch (e) {
        err.hidden = false;
        err.textContent = 'That is not valid JSON.';
        return;
      }
      ta.value = ''; // clear immediately after parsing
      try {
        var af = normalizeAutofill(parsed); // schema_version + field contract
        var gated = applyReviewedGate(af.fields, af.reviewed);
        pack = {
          heading: 'Pasted pack' + (af.reviewed ? ' (reviewed)' : ' (unreviewed — preview only)'),
          reviewed: af.reviewed,
          fields: gated,
          omittedCount: af.omittedCount,
        };
        review();
      } catch (e2) {
        pack = null;
        err.hidden = false;
        err.textContent = 'Rejected: ' + (e2 && e2.message ? e2.message : 'unsupported pack format') + '.';
      }
    });
    closeBtn.addEventListener('click', reset);

    box.appendChild(loadBtn);
    box.appendChild(closeBtn);
    shadow.appendChild(box);
    (document.body || document.documentElement).appendChild(host);
  }

  function review() {
    if (!pack) return;
    var scan = scanFields(document);
    var proposals = buildProposals(pack.fields || [], scan.fillable);
    var previewOnly = pack.reviewed !== true;

    renderOverlay({
      doc: document,
      pack: pack,
      proposals: proposals,
      pageFields: scan.fillable,
      excluded: scan.excluded,
      previewOnly: previewOnly,
      omittedCount: pack.omittedCount || 0,
      controller: {
        onAccept: function (proposal, pageIndex) {
          if (previewOnly) return { ok: false, error: 'Preview only — pack not reviewed.' };
          var d = scan.fillable[pageIndex];
          if (!d || !d.el) return { ok: false, error: 'Target field not found.' };
          var v = proposal.value;
          if (proposal.type === 'select') {
            var sel = proposal.selectResolution;
            if (!sel || sel.status !== 'ok') return { ok: false, error: 'No single matching option.' };
            v = sel.option.value;
          }
          try {
            writeValue(d.el, v);
            return { ok: true };
          } catch (e) {
            return { ok: false, error: e && e.name === 'RefusedWrite' ? 'Refused: ' + e.message : 'Write failed.' };
          }
        },
        onSkip: function () {},
        onPickTarget: function () {},
        onClose: reset,
      },
    });
  }

  openPasteUI();
})();
})();
