// Dependency-free bundler for the two injected scripts.
//
// content.js and bookmarklet.js run in a plain (non-module) script context, so
// they cannot use ES imports. This concatenates the relevant lib/* modules (which
// ARE ES modules, for the service worker and the tests) with a bootstrap, strips
// import/export keywords, and wraps the result in one strict-mode IIFE.
//
//   node build.js          -> write extension/content.js + extension/bookmarklet.js
//   node build.js --check   -> exit non-zero if either file is stale
//
// The test tests/build.test.js also calls buildBundle() and compares to disk.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));

export const BUNDLES = {
  'content.js': {
    libs: ['normalize.js', 'scoring.js', 'classify.js', 'overlay.js'],
    bootstrap: 'src/content.bootstrap.js',
  },
  'bookmarklet.js': {
    libs: ['normalize.js', 'policy.js', 'packschema.js', 'scoring.js', 'classify.js', 'overlay.js'],
    bootstrap: 'src/bookmarklet.bootstrap.js',
  },
};

function stripModuleSyntax(src) {
  return src
    .split('\n')
    .filter((line) => !/^\s*import\s.+from\s.+;?\s*$/.test(line))
    .filter((line) => !/^\s*import\s+['"].+['"];?\s*$/.test(line))
    .filter((line) => !/^\s*export\s*\{[^}]*\}\s*;?\s*$/.test(line))
    .map((line) => line.replace(/^(\s*)export\s+(?!default)/, '$1'))
    .join('\n');
}

export function buildBundle(name) {
  const spec = BUNDLES[name];
  if (!spec) throw new Error('unknown bundle: ' + name);

  const parts = [];
  parts.push('// GENERATED by build.js from lib modules + ' + spec.bootstrap + ' -- DO NOT EDIT.');
  parts.push('// Regenerate: node build.js');
  parts.push('(function () {');
  parts.push("'use strict';");

  for (const lib of spec.libs) {
    const src = readFileSync(join(HERE, 'lib', lib), 'utf8');
    parts.push('// ---- lib/' + lib + ' ----');
    parts.push(stripModuleSyntax(src).trim());
  }

  const boot = readFileSync(join(HERE, spec.bootstrap), 'utf8');
  parts.push('// ---- ' + spec.bootstrap + ' ----');
  parts.push(stripModuleSyntax(boot).trim());

  parts.push('})();');
  return parts.join('\n') + '\n';
}

export function buildAll() {
  const out = {};
  for (const name of Object.keys(BUNDLES)) out[name] = buildBundle(name);
  return out;
}

function main() {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [name, content] of Object.entries(buildAll())) {
    const path = join(HERE, name);
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      /* missing */
    }
    if (check) {
      if (current !== content) {
        stale += 1;
        process.stderr.write(`stale: ${name}\n`);
      }
    } else {
      writeFileSync(path, content);
      process.stdout.write(`wrote: ${name} (${content.length} bytes)\n`);
    }
  }
  if (check && stale) process.exit(1);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
